[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "xpid"
version = "2.1.4"
description = "Detector for XH-pi interactions in protein structures."
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
license-files = ["LICENSE"]
dependencies = [
    "gemmi",
    "numpy"
]

[project.urls]
Homepage = "https://github.com/SeanWang5868/xpid"
Repository = "https://github.com/SeanWang5868/xpid"
Issues = "https://github.com/SeanWang5868/xpid/issues"

[project.optional-dependencies]
parquet = [
    "pandas",
    "pyarrow"
]
test = [
    "pytest"
]
demo = [
    "pandas",
    "matplotlib"
]

[project.scripts]
xpid = "xpid.cli:main"

[tool.setuptools.packages.find]
where = ["src"]
include = ["xpid*"]
namespaces = false

[tool.setuptools.package-data]
xpid = ["monomers/*"]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["test"]
