#!/usr/bin/env python3
"""Generate residue- and donor-level evidence tables for Results section 2.2.

The script consumes one accepted ``generate_background.py`` output directory
and writes five manuscript-facing CSV tables:

* residue_contribution.csv
* residue_atom_propensity.csv
* donor_class_propensity.csv
* donor_class_geometry.csv
* backbone_nh_by_residue.csv

Two contact scopes are deliberately kept distinct.  Counts labelled
``representative_chain_contact`` include a positive pair when either its donor
or acceptor is on a PISCES-selected chain.  Rates and propensities use only
``selected_donor`` pairs, because their denominator is the eligible donor or
residue population on PISCES-selected chains.  The two scopes must not be
mixed in a numerator/denominator ratio.
"""

from __future__ import annotations

import argparse
from collections import defaultdict
import csv
from datetime import datetime, timezone
import json
import math
from pathlib import Path
import sys
from typing import Any, Dict, Iterable, Iterator, List, Mapping, MutableMapping, Sequence, Set, Tuple

try:
    import numpy as np
    import pandas as pd
    import pyarrow.parquet as pq
except ImportError as exc:  # pragma: no cover - environment error path
    raise SystemExit(
        "This analysis requires numpy, pandas and pyarrow in the active "
        "environment."
    ) from exc


STANDARD_AMINO_ACIDS: Tuple[str, ...] = (
    "ALA", "ARG", "ASN", "ASP", "CYS", "GLN", "GLU", "GLY", "HIS", "ILE",
    "LEU", "LYS", "MET", "PHE", "PRO", "SER", "THR", "TRP", "TYR", "VAL",
)

PRIMARY_DONOR_CLASSES: Set[str] = {
    "Methyl C-H",
    "Methylene C-H",
    "Methine C-H",
    "Aromatic C-H",
    "C-alpha C-H",
    "Backbone N-H",
    "Amide side-chain N-H",
    "Aromatic side-chain N-H",
    "Hydroxyl O-H",
    "Thiol S-H",
}

DONOR_CLASS_ORDER: Tuple[str, ...] = (
    "Methyl C-H",
    "Methylene C-H",
    "Methine C-H",
    "Aromatic C-H",
    "C-alpha C-H",
    "Backbone N-H",
    "Amide side-chain N-H",
    "Aromatic side-chain N-H",
    "Hydroxyl O-H",
    "Thiol S-H",
)

GEOMETRY_METRICS: Tuple[Tuple[str, str], ...] = (
    ("dist_X_plane", "dist_X_plane_A"),
    ("dist_X_centroid", "dist_X_centroid_A"),
    ("projection_distance", "projection_distance_A"),
    ("angle_XPCN", "angle_XPCN_deg"),
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Generate four residue/donor evidence tables from an accepted "
            "Section 02 background run."
        )
    )
    parser.add_argument(
        "--background",
        required=True,
        type=Path,
        help="Path to output/background_<timestamp>.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        help=(
            "Output directory. Default: "
            "<background>/analysis/residue_donor"
        ),
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Replace the six files generated by this script if they exist.",
    )
    parser.add_argument(
        "--bootstrap",
        type=int,
        default=2000,
        help="PDB-structure bootstrap replicates for residue and donor-class rates.",
    )
    parser.add_argument("--seed", type=int, default=20260802)
    return parser.parse_args()


def as_int(value: Any) -> int:
    if value is None or (isinstance(value, float) and math.isnan(value)):
        return 0
    return int(value)


def as_float(value: Any, default: float = 0.0) -> float:
    if value is None:
        return default
    try:
        result = float(value)
    except (TypeError, ValueError):
        return default
    return default if math.isnan(result) else result


def safe_ratio(numerator: float, denominator: float, scale: float = 1.0) -> Any:
    if denominator == 0:
        return ""
    return numerator / denominator * scale


def write_csv(path: Path, rows: Sequence[Mapping[str, Any]]) -> None:
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    fields: List[str] = []
    seen: Set[str] = set()
    for row in rows:
        for field in row:
            if field not in seen:
                fields.append(field)
                seen.add(field)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def parquet_files(directory: Path) -> List[Path]:
    files = sorted(directory.glob("*.parquet"))
    if not files:
        raise FileNotFoundError(f"No Parquet files found in {directory}")
    return files


def read_columns(path: Path, columns: Sequence[str]) -> pd.DataFrame:
    schema_names = set(pq.read_schema(path).names)
    missing = [column for column in columns if column not in schema_names]
    if missing:
        raise ValueError(f"{path} is missing required columns: {missing}")
    return pq.read_table(path, columns=list(columns)).to_pandas()


def is_primary_donor(
    donor_class: Any,
    residue_name: Any,
    cys_assignment: Any,
) -> bool:
    donor_class = str(donor_class or "")
    residue_name = str(residue_name or "").upper()
    if donor_class not in PRIMARY_DONOR_CLASSES:
        return False
    if residue_name not in STANDARD_AMINO_ACIDS:
        return False
    # Internal proline N is tertiary in a peptide and has no N-H hydrogen.
    # Older element summaries classified every atom named N as Backbone N-H;
    # keep that legacy scope auditable, but do not propagate it here.
    if donor_class == "Backbone N-H" and residue_name == "PRO":
        return False
    if donor_class == "Thiol S-H":
        return str(cys_assignment or "") == "putative_free_thiol"
    return True


def is_legacy_element_primary_donor(
    donor_class: Any,
    cys_assignment: Any,
) -> bool:
    """Reproduce the earlier element-table scope for exact reconciliation."""
    donor_class = str(donor_class or "")
    if donor_class not in PRIMARY_DONOR_CLASSES:
        return False
    if donor_class == "Thiol S-H":
        return str(cys_assignment or "") == "putative_free_thiol"
    return True


def chemical_exclusion_reason(donor_class: Any, residue_name: Any) -> str:
    donor_class = str(donor_class or "")
    residue_name = str(residue_name or "").upper()
    if residue_name not in STANDARD_AMINO_ACIDS:
        return "nonstandard_residue_in_legacy_standard_class"
    if donor_class == "Backbone N-H" and residue_name == "PRO":
        return "internal_proline_N_has_no_backbone_NH"
    return "other_primary_scope_difference"


def conservative_cys_assignment(values: Iterable[Any]) -> str:
    assignments = {
        str(value)
        for value in values
        if value is not None and str(value) not in {"", "nan", "None"}
    }
    if "ambiguous_possible_covalent_modification" in assignments:
        return "ambiguous_possible_covalent_modification"
    if "putative_free_thiol" in assignments:
        return "putative_free_thiol"
    if "not_available_as_thiol" in assignments:
        return "not_available_as_thiol"
    return ""


def collapse_positive_pairs(frame: pd.DataFrame) -> Tuple[pd.DataFrame, int]:
    """Return one positive representative per physical spatial pair."""
    if frame.empty:
        return frame, 0
    frame = frame[frame["is_positive_pair"].fillna(0).astype(int) == 1].copy()
    if frame.empty:
        return frame, 0
    duplicate_count = int(frame.duplicated("spatial_pair_id", keep=False).sum())
    frame["combined_occupancy"] = pd.to_numeric(
        frame["combined_occupancy"], errors="coerce"
    ).fillna(-1.0)
    frame.sort_values(
        ["spatial_pair_id", "combined_occupancy"],
        ascending=[True, False],
        kind="mergesort",
        inplace=True,
    )
    return frame.drop_duplicates("spatial_pair_id", keep="first"), duplicate_count


def collapse_donor_sites(frame: pd.DataFrame) -> Tuple[pd.DataFrame, int]:
    """Collapse alternate conformers to one chemically conservative site."""
    if frame.empty:
        return frame, 0
    duplicate_count = int(frame.duplicated("donor_site_id", keep=False).sum())
    frame = frame.copy()
    frame["occupancy"] = pd.to_numeric(frame["occupancy"], errors="coerce").fillna(-1.0)
    frame.sort_values(
        ["donor_site_id", "occupancy"],
        ascending=[True, False],
        kind="mergesort",
        inplace=True,
    )
    representatives = frame.drop_duplicates("donor_site_id", keep="first").copy()
    eligible_any = frame.groupby("donor_site_id", sort=False)["eligible"].max()
    cys_assignment = frame.groupby("donor_site_id", sort=False)[
        "cys_sg_thiol_assignment"
    ].agg(conservative_cys_assignment)
    representatives["eligible"] = representatives["donor_site_id"].map(eligible_any)
    representatives["cys_sg_thiol_assignment"] = representatives["donor_site_id"].map(
        cys_assignment
    )
    return representatives, duplicate_count


def new_positive_bucket() -> Dict[str, Any]:
    return {
        "pair_count": 0,
        "variant_weighted_pair_count": 0.0,
        "contact_count": 0,
        "contact_occupancy_weight": 0.0,
        "donor_sites": set(),
        "residue_positions": set(),
        "weighted_donor_sites": {},
        "weighted_residue_positions": {},
        "pdb_ids": set(),
    }


def add_positive(
    bucket: MutableMapping[str, Any],
    row: Mapping[str, Any],
) -> None:
    variant_weight = as_float(row.get("donor_residue_variant_weight"), 1.0)
    donor_site_id = str(row.get("donor_site_id") or "")
    residue_position_id = str(row.get("donor_residue_position_id") or "")
    bucket["pair_count"] += 1
    bucket["variant_weighted_pair_count"] += variant_weight
    bucket["contact_count"] += max(1, as_int(row.get("positive_contact_count")))
    bucket["contact_occupancy_weight"] += as_float(
        row.get("positive_contact_occupancy_weight"), 0.0
    )
    if donor_site_id:
        bucket["donor_sites"].add(donor_site_id)
        bucket["weighted_donor_sites"][donor_site_id] = max(
            variant_weight,
            bucket["weighted_donor_sites"].get(donor_site_id, 0.0),
        )
    if residue_position_id:
        bucket["residue_positions"].add(residue_position_id)
        bucket["weighted_residue_positions"][residue_position_id] = max(
            variant_weight,
            bucket["weighted_residue_positions"].get(residue_position_id, 0.0),
        )
    pdb_id = str(row.get("pdb_id") or "")
    if pdb_id:
        bucket["pdb_ids"].add(pdb_id)


def summarize_values(values: Sequence[float]) -> Dict[str, Any]:
    finite = np.asarray([value for value in values if math.isfinite(value)], dtype=float)
    if finite.size == 0:
        return {
            "n": 0,
            "mean": "",
            "sd": "",
            "median": "",
            "q1": "",
            "q3": "",
            "p05": "",
            "p95": "",
            "min": "",
            "max": "",
        }
    return {
        "n": int(finite.size),
        "mean": float(np.mean(finite)),
        "sd": float(np.std(finite, ddof=1)) if finite.size > 1 else 0.0,
        "median": float(np.median(finite)),
        "q1": float(np.quantile(finite, 0.25)),
        "q3": float(np.quantile(finite, 0.75)),
        "p05": float(np.quantile(finite, 0.05)),
        "p95": float(np.quantile(finite, 0.95)),
        "min": float(np.min(finite)),
        "max": float(np.max(finite)),
    }


def cluster_ratio_interval(
    numerator: np.ndarray,
    denominator: np.ndarray,
    bootstrap_weights: np.ndarray,
    scale: float,
) -> Tuple[float, float, float]:
    """Ratio and percentile CI after resampling PDB structures."""
    denominator_total = float(denominator.sum())
    point = (
        float(numerator.sum()) / denominator_total * scale
        if denominator_total else float("nan")
    )
    sampled_denominator = bootstrap_weights @ denominator
    sampled_numerator = bootstrap_weights @ numerator
    valid = sampled_denominator > 0
    sampled = sampled_numerator[valid] / sampled_denominator[valid] * scale
    return (
        point,
        float(np.quantile(sampled, 0.025)),
        float(np.quantile(sampled, 0.975)),
    )


def main() -> int:
    args = parse_args()
    root = args.background.resolve()
    out = (args.output or root / "analysis" / "residue_donor").resolve()
    datasets = root / "datasets"
    input_qc_path = root / "qc_report.json"
    metadata_path = root / "background_metadata.json"
    if not input_qc_path.exists() or not metadata_path.exists():
        raise FileNotFoundError(
            "--background must contain qc_report.json and background_metadata.json"
        )
    input_qc = json.loads(input_qc_path.read_text(encoding="utf-8"))
    background_metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
    if int(background_metadata.get("output_schema_version", 0)) < 8:
        raise ValueError("Schema v8 is required for the final residue/donor analysis")
    if input_qc.get("status") != "pass":
        raise ValueError(
            f"Background QC status is {input_qc.get('status')!r}; expected 'pass'."
        )

    output_files = [
        out / "residue_contribution.csv",
        out / "residue_atom_propensity.csv",
        out / "donor_class_propensity.csv",
        out / "donor_class_geometry.csv",
        out / "backbone_nh_by_residue.csv",
        out / "analysis_metadata.json",
        out / "qc_report.json",
    ]
    existing = [path for path in output_files if path.exists()]
    if existing and not args.force:
        raise FileExistsError(
            "Output already exists; add --force to replace only this script's "
            f"generated files: {existing[0]}"
        )
    out.mkdir(parents=True, exist_ok=True)

    selected_positive_by_residue: Dict[str, Dict[str, Any]] = defaultdict(new_positive_bucket)
    main_positive_by_residue: Dict[str, Dict[str, Any]] = defaultdict(new_positive_bucket)
    selected_positive_by_atom: Dict[Tuple[str, str, str, str, str], Dict[str, Any]] = defaultdict(new_positive_bucket)
    main_positive_by_atom: Dict[Tuple[str, str, str, str, str], Dict[str, Any]] = defaultdict(new_positive_bucket)
    selected_backbone_by_residue: Dict[str, Dict[str, Any]] = defaultdict(new_positive_bucket)
    main_backbone_by_residue: Dict[str, Dict[str, Any]] = defaultdict(new_positive_bucket)
    geometry: Dict[Tuple[str, str, str, str], Dict[str, Any]] = defaultdict(
        lambda: {
            "values": defaultdict(list),
            "pdb_ids": set(),
            "hudson_count": 0,
            "plevin_count": 0,
            "both_count": 0,
        }
    )
    selected_positive_donor_ids: Set[str] = set()
    main_positive_donor_ids: Set[str] = set()
    duplicate_positive_rows = 0
    selected_primary_positive_pair_count = 0
    main_primary_positive_pair_count = 0
    selected_legacy_excluded_positive: Dict[str, int] = defaultdict(int)
    main_legacy_excluded_positive: Dict[str, int] = defaultdict(int)
    selected_pair_by_residue_pdb: Dict[Tuple[str, str], int] = defaultdict(int)
    selected_sites_by_residue_pdb: Dict[Tuple[str, str], Set[str]] = defaultdict(set)
    selected_pair_by_class_pdb: Dict[Tuple[str, str], int] = defaultdict(int)
    selected_sites_by_class_pdb: Dict[Tuple[str, str], Set[str]] = defaultdict(set)

    spatial_columns = [
        "pdb_id",
        "spatial_pair_id",
        "donor_site_id",
        "donor_residue_position_id",
        "x_residue_name",
        "x_atom_name",
        "x_element",
        "donor_class",
        "donor_treatment",
        "donor_residue_variant_weight",
        "donor_on_selected_chain",
        "acceptor_on_selected_chain",
        "either_endpoint_on_selected_chain",
        "dist_X_plane",
        "dist_X_centroid",
        "projection_distance",
        "angle_XPCN",
        "cys_sg_thiol_assignment",
        "combined_occupancy",
        "positive_contact_count",
        "positive_contact_occupancy_weight",
        "is_positive_pair",
        "is_hudson_positive_pair",
        "is_plevin_positive_pair",
    ]

    spatial_files = parquet_files(datasets / "spatial_pair_background")
    for index, path in enumerate(spatial_files, start=1):
        frame = read_columns(path, spatial_columns)
        frame, duplicates = collapse_positive_pairs(frame)
        duplicate_positive_rows += duplicates
        if frame.empty:
            continue
        for row in frame.to_dict("records"):
            is_main = as_int(row["either_endpoint_on_selected_chain"]) == 1
            is_selected_donor = as_int(row["donor_on_selected_chain"]) == 1
            corrected_primary = is_primary_donor(
                row["donor_class"],
                row["x_residue_name"],
                row["cys_sg_thiol_assignment"],
            )
            legacy_primary = is_legacy_element_primary_donor(
                row["donor_class"], row["cys_sg_thiol_assignment"]
            )
            if legacy_primary and not corrected_primary:
                reason = chemical_exclusion_reason(
                    row["donor_class"], row["x_residue_name"]
                )
                detail = "|".join(
                    (
                        reason,
                        str(row["x_residue_name"]).upper(),
                        str(row["donor_class"]),
                        str(row["x_element"]),
                    )
                )
                if is_selected_donor:
                    selected_legacy_excluded_positive[detail] += 1
                if is_main:
                    main_legacy_excluded_positive[detail] += 1
            if not corrected_primary:
                continue
            donor_class = str(row["donor_class"])
            residue_name = str(row["x_residue_name"]).upper()
            atom_key = (
                residue_name,
                str(row["x_atom_name"]).upper(),
                donor_class,
                str(row["x_element"]),
                str(row["donor_treatment"]),
            )
            class_key = (
                donor_class,
                str(row["x_element"]),
                str(row["donor_treatment"]),
            )

            if is_main:
                main_primary_positive_pair_count += 1
                main_positive_donor_ids.add(str(row["donor_site_id"]))
                add_positive(main_positive_by_residue[residue_name], row)
                add_positive(main_positive_by_atom[atom_key], row)
                if donor_class == "Backbone N-H":
                    add_positive(main_backbone_by_residue[residue_name], row)

            if is_selected_donor:
                selected_primary_positive_pair_count += 1
                selected_positive_donor_ids.add(str(row["donor_site_id"]))
                add_positive(selected_positive_by_residue[residue_name], row)
                add_positive(selected_positive_by_atom[atom_key], row)
                pdb_id = str(row["pdb_id"])
                selected_pair_by_residue_pdb[(pdb_id, residue_name)] += 1
                residue_position_id = str(row["donor_residue_position_id"] or "")
                if residue_position_id:
                    selected_sites_by_residue_pdb[(pdb_id, residue_name)].add(
                        residue_position_id
                    )
                selected_pair_by_class_pdb[(pdb_id, donor_class)] += 1
                donor_site_id = str(row["donor_site_id"] or "")
                if donor_site_id:
                    selected_sites_by_class_pdb[(pdb_id, donor_class)].add(
                        donor_site_id
                    )
                if donor_class == "Backbone N-H":
                    add_positive(selected_backbone_by_residue[residue_name], row)

            for scope, include in (
                ("representative_chain_contact", is_main),
                ("selected_donor", is_selected_donor),
            ):
                if not include:
                    continue
                bucket = geometry[(scope,) + class_key]
                bucket["pdb_ids"].add(str(row["pdb_id"]))
                hudson = as_int(row["is_hudson_positive_pair"])
                plevin = as_int(row["is_plevin_positive_pair"])
                bucket["hudson_count"] += hudson
                bucket["plevin_count"] += plevin
                bucket["both_count"] += int(hudson == 1 and plevin == 1)
                for source_name, output_name in GEOMETRY_METRICS:
                    value = as_float(row.get(source_name), float("nan"))
                    if math.isfinite(value):
                        bucket["values"][output_name].append(value)

        if index % 500 == 0:
            print(f"Read spatial positives from {index}/{len(spatial_files)} structures", file=sys.stderr)

    residue_background: Dict[str, Dict[str, Any]] = defaultdict(
        lambda: {
            "raw_variant_rows": 0,
            "primary_position_count": 0,
            "variant_weighted_count": 0.0,
            "pdb_ids": set(),
        }
    )
    residue_background_by_pdb: Dict[Tuple[str, str], int] = defaultdict(int)
    residue_columns = [
        "pdb_id",
        "residue_name",
        "residue_position_id",
        "is_standard_amino_acid",
        "is_selected_chain",
        "residue_variant_weight",
        "is_primary_residue_variant",
    ]
    residue_files = parquet_files(datasets / "residue_background")
    for index, path in enumerate(residue_files, start=1):
        frame = read_columns(path, residue_columns)
        frame = frame[
            (frame["is_standard_amino_acid"].fillna(0).astype(int) == 1)
            & (frame["is_selected_chain"].fillna(0).astype(int) == 1)
        ]
        for row in frame.to_dict("records"):
            residue_name = str(row["residue_name"]).upper()
            if residue_name not in STANDARD_AMINO_ACIDS:
                continue
            bucket = residue_background[residue_name]
            bucket["raw_variant_rows"] += 1
            bucket["primary_position_count"] += as_int(row["is_primary_residue_variant"])
            residue_background_by_pdb[(
                str(row["pdb_id"]), residue_name
            )] += as_int(row["is_primary_residue_variant"])
            bucket["variant_weighted_count"] += as_float(row["residue_variant_weight"], 1.0)
            bucket["pdb_ids"].add(str(row["pdb_id"]))
        if index % 500 == 0:
            print(f"Read residue background from {index}/{len(residue_files)} structures", file=sys.stderr)

    donor_background_by_atom: Dict[Tuple[str, str, str, str, str], Dict[str, Any]] = defaultdict(
        lambda: {
            "eligible_site_count": 0,
            "variant_weighted_eligible_site_count": 0.0,
            "pdb_ids": set(),
        }
    )
    backbone_background_by_residue: Dict[str, Dict[str, Any]] = defaultdict(
        lambda: {
            "eligible_site_count": 0,
            "variant_weighted_eligible_site_count": 0.0,
            "pdb_ids": set(),
        }
    )
    selected_positive_ids_found: Set[str] = set()
    main_positive_ids_found: Set[str] = set()
    duplicate_donor_conformer_rows = 0
    selected_primary_eligible_donor_count = 0
    selected_legacy_excluded_eligible: Dict[str, int] = defaultdict(int)
    donor_background_by_class_pdb: Dict[Tuple[str, str], int] = defaultdict(int)

    donor_columns = [
        "pdb_id",
        "residue_name",
        "atom_name",
        "element",
        "occupancy",
        "donor_class",
        "donor_treatment",
        "donor_site_id",
        "is_selected_chain",
        "eligible",
        "cys_sg_thiol_assignment",
        "residue_variant_weight",
    ]
    donor_files = parquet_files(datasets / "donor_site_background")
    for index, path in enumerate(donor_files, start=1):
        frame = read_columns(path, donor_columns)
        frame, duplicates = collapse_donor_sites(frame)
        duplicate_donor_conformer_rows += duplicates
        for row in frame.to_dict("records"):
            donor_site_id = str(row["donor_site_id"])
            if donor_site_id in selected_positive_donor_ids:
                selected_positive_ids_found.add(donor_site_id)
            if donor_site_id in main_positive_donor_ids:
                main_positive_ids_found.add(donor_site_id)
            if as_int(row["is_selected_chain"]) != 1 or as_int(row["eligible"]) != 1:
                continue
            corrected_primary = is_primary_donor(
                row["donor_class"],
                row["residue_name"],
                row["cys_sg_thiol_assignment"],
            )
            legacy_primary = is_legacy_element_primary_donor(
                row["donor_class"], row["cys_sg_thiol_assignment"]
            )
            if legacy_primary and not corrected_primary:
                reason = chemical_exclusion_reason(
                    row["donor_class"], row["residue_name"]
                )
                detail = "|".join(
                    (
                        reason,
                        str(row["residue_name"]).upper(),
                        str(row["donor_class"]),
                        str(row["element"]),
                    )
                )
                selected_legacy_excluded_eligible[detail] += 1
            if not corrected_primary:
                continue
            residue_name = str(row["residue_name"]).upper()
            donor_class = str(row["donor_class"])
            atom_key = (
                residue_name,
                str(row["atom_name"]).upper(),
                donor_class,
                str(row["element"]),
                str(row["donor_treatment"]),
            )
            weight = as_float(row["residue_variant_weight"], 1.0)
            bucket = donor_background_by_atom[atom_key]
            bucket["eligible_site_count"] += 1
            bucket["variant_weighted_eligible_site_count"] += weight
            bucket["pdb_ids"].add(str(row["pdb_id"]))
            selected_primary_eligible_donor_count += 1
            donor_background_by_class_pdb[(
                str(row["pdb_id"]), donor_class
            )] += 1
            if donor_class == "Backbone N-H":
                bb = backbone_background_by_residue[residue_name]
                bb["eligible_site_count"] += 1
                bb["variant_weighted_eligible_site_count"] += weight
                bb["pdb_ids"].add(str(row["pdb_id"]))
        if index % 500 == 0:
            print(f"Read donor background from {index}/{len(donor_files)} structures", file=sys.stderr)

    selected_positive_total = sum(
        bucket["pair_count"] for bucket in selected_positive_by_residue.values()
    )
    main_positive_total = sum(
        bucket["pair_count"] for bucket in main_positive_by_residue.values()
    )

    structure_manifest = pd.read_csv(root / "structure_manifest.csv")
    pdb_ids = structure_manifest.loc[
        structure_manifest["status"] == "ok", "pdb_id"
    ].astype(str).tolist()
    rng = np.random.default_rng(args.seed)
    bootstrap_weights = rng.multinomial(
        len(pdb_ids), np.full(len(pdb_ids), 1.0 / len(pdb_ids)),
        size=args.bootstrap,
    ).astype(float)

    def counts(mapping: Mapping[Tuple[str, str], Any], label: str) -> np.ndarray:
        values = []
        for pdb_id in pdb_ids:
            value = mapping.get((pdb_id, label), 0)
            values.append(len(value) if isinstance(value, set) else value)
        return np.asarray(values, dtype=float)

    residue_rows: List[Dict[str, Any]] = []
    for residue_name in STANDARD_AMINO_ACIDS:
        background = residue_background[residue_name]
        selected = selected_positive_by_residue[residue_name]
        main_scope = main_positive_by_residue[residue_name]
        weighted_participating = sum(selected["weighted_residue_positions"].values())
        weighted_residue_count = background["variant_weighted_count"]
        pair_rate, pair_low, pair_high = cluster_ratio_interval(
            counts(selected_pair_by_residue_pdb, residue_name),
            counts(residue_background_by_pdb, residue_name),
            bootstrap_weights, 1000.0,
        )
        participation, participation_low, participation_high = cluster_ratio_interval(
            counts(selected_sites_by_residue_pdb, residue_name),
            counts(residue_background_by_pdb, residue_name),
            bootstrap_weights, 100.0,
        )
        residue_rows.append(
            {
                "residue_name": residue_name,
                "selected_chain_primary_residue_position_count": background[
                    "primary_position_count"
                ],
                "selected_chain_residue_variant_weighted_count": weighted_residue_count,
                "selected_chain_raw_residue_variant_row_count": background[
                    "raw_variant_rows"
                ],
                "selected_donor_positive_pair_count": selected["pair_count"],
                "selected_donor_variant_weighted_positive_pair_count": selected[
                    "variant_weighted_pair_count"
                ],
                "selected_donor_positive_contact_record_count": selected[
                    "contact_count"
                ],
                "selected_donor_participating_residue_position_count": len(
                    selected["residue_positions"]
                ),
                "selected_donor_variant_weighted_participating_residue_count": weighted_participating,
                "positive_pairs_per_1000_primary_residue_positions": safe_ratio(
                    selected["pair_count"], background["primary_position_count"], 1000.0
                ),
                "positive_pairs_per_1000_residues_bootstrap_estimate": pair_rate,
                "positive_pairs_per_1000_residues_ci95_low": pair_low,
                "positive_pairs_per_1000_residues_ci95_high": pair_high,
                "variant_weighted_positive_pairs_per_1000_residues": safe_ratio(
                    selected["variant_weighted_pair_count"], weighted_residue_count, 1000.0
                ),
                "participating_residue_percent": safe_ratio(
                    len(selected["residue_positions"]),
                    background["primary_position_count"],
                    100.0,
                ),
                "participating_residue_percent_bootstrap_estimate": participation,
                "participating_residue_percent_ci95_low": participation_low,
                "participating_residue_percent_ci95_high": participation_high,
                "variant_weighted_participating_residue_percent": safe_ratio(
                    weighted_participating, weighted_residue_count, 100.0
                ),
                "selected_donor_positive_pair_composition_percent": safe_ratio(
                    selected["pair_count"], selected_positive_total, 100.0
                ),
                "representative_chain_contact_positive_pair_count": main_scope[
                    "pair_count"
                ],
                "representative_chain_contact_positive_pair_composition_percent": safe_ratio(
                    main_scope["pair_count"], main_positive_total, 100.0
                ),
                "structures_with_selected_chain_residue": len(background["pdb_ids"]),
                "structures_with_selected_donor_positive_pair": len(selected["pdb_ids"]),
            }
        )

    atom_rows: List[Dict[str, Any]] = []
    atom_keys = sorted(
        set(donor_background_by_atom)
        | set(selected_positive_by_atom)
        | set(main_positive_by_atom),
        key=lambda key: (
            STANDARD_AMINO_ACIDS.index(key[0]) if key[0] in STANDARD_AMINO_ACIDS else 999,
            DONOR_CLASS_ORDER.index(key[2]) if key[2] in DONOR_CLASS_ORDER else 999,
            key[1],
        ),
    )
    for key in atom_keys:
        residue_name, atom_name, donor_class, element, treatment = key
        background = donor_background_by_atom[key]
        selected = selected_positive_by_atom[key]
        main_scope = main_positive_by_atom[key]
        eligible = background["eligible_site_count"]
        weighted_eligible = background["variant_weighted_eligible_site_count"]
        participating = len(selected["donor_sites"])
        weighted_participating = sum(selected["weighted_donor_sites"].values())
        atom_rows.append(
            {
                "residue_name": residue_name,
                "atom_name": atom_name,
                "donor_class": donor_class,
                "element": element,
                "donor_treatment": treatment,
                "selected_chain_eligible_donor_site_count": eligible,
                "selected_chain_variant_weighted_eligible_donor_site_count": weighted_eligible,
                "selected_donor_participating_site_count": participating,
                "selected_donor_variant_weighted_participating_site_count": weighted_participating,
                "selected_donor_positive_pair_count": selected["pair_count"],
                "selected_donor_variant_weighted_positive_pair_count": selected[
                    "variant_weighted_pair_count"
                ],
                "positive_pairs_per_1000_eligible_donor_sites": safe_ratio(
                    selected["pair_count"], eligible, 1000.0
                ),
                "variant_weighted_positive_pairs_per_1000_donor_sites": safe_ratio(
                    selected["variant_weighted_pair_count"], weighted_eligible, 1000.0
                ),
                "participating_donor_site_percent": safe_ratio(
                    participating, eligible, 100.0
                ),
                "variant_weighted_participating_donor_site_percent": safe_ratio(
                    weighted_participating, weighted_eligible, 100.0
                ),
                "positive_pairs_per_participating_donor_site": safe_ratio(
                    selected["pair_count"], participating
                ),
                "selected_donor_positive_pair_composition_percent": safe_ratio(
                    selected["pair_count"], selected_positive_total, 100.0
                ),
                "representative_chain_contact_positive_pair_count": main_scope[
                    "pair_count"
                ],
                "structures_with_eligible_donor_site": len(background["pdb_ids"]),
                "structures_with_selected_donor_positive_pair": len(selected["pdb_ids"]),
            }
        )

    donor_class_rows: List[Dict[str, Any]] = []
    for donor_class in DONOR_CLASS_ORDER:
        keys = [key for key in atom_keys if key[2] == donor_class]
        if not keys:
            continue
        eligible = sum(
            donor_background_by_atom[key]["eligible_site_count"] for key in keys
        )
        participating_sites = set().union(*(
            selected_positive_by_atom[key]["donor_sites"] for key in keys
        ))
        selected_pairs = sum(
            selected_positive_by_atom[key]["pair_count"] for key in keys
        )
        main_pairs = sum(main_positive_by_atom[key]["pair_count"] for key in keys)
        eligible_structures = set().union(*(
            donor_background_by_atom[key]["pdb_ids"] for key in keys
        ))
        positive_structures = set().union(*(
            selected_positive_by_atom[key]["pdb_ids"] for key in keys
        ))
        pair_rate, pair_low, pair_high = cluster_ratio_interval(
            counts(selected_pair_by_class_pdb, donor_class),
            counts(donor_background_by_class_pdb, donor_class),
            bootstrap_weights, 1000.0,
        )
        participation, participation_low, participation_high = cluster_ratio_interval(
            counts(selected_sites_by_class_pdb, donor_class),
            counts(donor_background_by_class_pdb, donor_class),
            bootstrap_weights, 100.0,
        )
        donor_class_rows.append({
            "donor_class": donor_class,
            "element": keys[0][3],
            "donor_treatment": ";".join(sorted({key[4] for key in keys})),
            "selected_chain_eligible_donor_site_count": eligible,
            "selected_donor_participating_site_count": len(participating_sites),
            "selected_donor_positive_pair_count": selected_pairs,
            "representative_chain_contact_positive_pair_count": main_pairs,
            "positive_pairs_per_1000_eligible_donor_sites": pair_rate,
            "positive_pairs_per_1000_eligible_sites_ci95_low": pair_low,
            "positive_pairs_per_1000_eligible_sites_ci95_high": pair_high,
            "participating_donor_site_percent": participation,
            "participating_donor_site_percent_ci95_low": participation_low,
            "participating_donor_site_percent_ci95_high": participation_high,
            "positive_pairs_per_participating_donor_site": safe_ratio(
                selected_pairs, len(participating_sites)
            ),
            "selected_donor_positive_pair_composition_percent": safe_ratio(
                selected_pairs, selected_positive_total, 100.0
            ),
            "representative_chain_contact_composition_percent": safe_ratio(
                main_pairs, main_positive_total, 100.0
            ),
            "structures_with_eligible_donor_site": len(eligible_structures),
            "structures_with_selected_donor_positive_pair": len(positive_structures),
            "independent_unit_for_ci": "PDB structure",
        })

    geometry_rows: List[Dict[str, Any]] = []
    geometry_order = {name: index for index, name in enumerate(DONOR_CLASS_ORDER)}
    for key in sorted(
        geometry,
        key=lambda item: (
            0 if item[0] == "representative_chain_contact" else 1,
            geometry_order.get(item[1], 999),
            item[2],
            item[3],
        ),
    ):
        scope, donor_class, element, treatment = key
        bucket = geometry[key]
        pair_count = max(
            [len(values) for values in bucket["values"].values()] or [0]
        )
        for _, output_name in GEOMETRY_METRICS:
            summary = summarize_values(bucket["values"].get(output_name, []))
            geometry_rows.append(
                {
                    "scope": scope,
                    "donor_class": donor_class,
                    "element": element,
                    "donor_treatment": treatment,
                    "metric": output_name,
                    "positive_pair_count_in_class": pair_count,
                    "metric_nonmissing_count": summary["n"],
                    "structure_count": len(bucket["pdb_ids"]),
                    "mean": summary["mean"],
                    "sd": summary["sd"],
                    "median": summary["median"],
                    "q1": summary["q1"],
                    "q3": summary["q3"],
                    "p05": summary["p05"],
                    "p95": summary["p95"],
                    "min": summary["min"],
                    "max": summary["max"],
                    "hudson_positive_pair_count": bucket["hudson_count"],
                    "plevin_positive_pair_count": bucket["plevin_count"],
                    "both_systems_positive_pair_count": bucket["both_count"],
                }
            )

    backbone_rows: List[Dict[str, Any]] = []
    for residue_name in STANDARD_AMINO_ACIDS:
        background = backbone_background_by_residue[residue_name]
        selected = selected_backbone_by_residue[residue_name]
        main_scope = main_backbone_by_residue[residue_name]
        eligible = background["eligible_site_count"]
        weighted_eligible = background["variant_weighted_eligible_site_count"]
        participating = len(selected["donor_sites"])
        weighted_participating = sum(selected["weighted_donor_sites"].values())
        backbone_rows.append(
            {
                "residue_name": residue_name,
                "selected_chain_eligible_backbone_NH_site_count": eligible,
                "selected_chain_variant_weighted_eligible_backbone_NH_site_count": weighted_eligible,
                "selected_donor_participating_backbone_NH_site_count": participating,
                "selected_donor_variant_weighted_participating_backbone_NH_site_count": weighted_participating,
                "selected_donor_backbone_NH_positive_pair_count": selected[
                    "pair_count"
                ],
                "selected_donor_variant_weighted_backbone_NH_positive_pair_count": selected[
                    "variant_weighted_pair_count"
                ],
                "backbone_NH_positive_pairs_per_1000_eligible_sites": safe_ratio(
                    selected["pair_count"], eligible, 1000.0
                ),
                "variant_weighted_backbone_NH_positive_pairs_per_1000_sites": safe_ratio(
                    selected["variant_weighted_pair_count"], weighted_eligible, 1000.0
                ),
                "backbone_NH_participating_site_percent": safe_ratio(
                    participating, eligible, 100.0
                ),
                "variant_weighted_backbone_NH_participating_site_percent": safe_ratio(
                    weighted_participating, weighted_eligible, 100.0
                ),
                "positive_pairs_per_participating_backbone_NH_site": safe_ratio(
                    selected["pair_count"], participating
                ),
                "representative_chain_contact_backbone_NH_positive_pair_count": main_scope[
                    "pair_count"
                ],
                "structures_with_eligible_backbone_NH": len(background["pdb_ids"]),
                "structures_with_selected_donor_backbone_NH_positive_pair": len(
                    selected["pdb_ids"]
                ),
                "interpretation_boundary": (
                    "not_applicable_internal_backbone_NH"
                    if residue_name == "PRO"
                    else "hydrogen_bond_competition_not_evaluated"
                ),
            }
        )

    expected_selected_donor_count = None
    expected_selected_positive_count = None
    element_counts_path = root / "analysis" / "element_level" / "element_funnel_counts.csv"
    if element_counts_path.exists():
        element_counts = pd.read_csv(element_counts_path)
        all_rows = element_counts[element_counts["donor_treatment"] == "all"]
        expected_selected_donor_count = int(all_rows["eligible_donor_site_count"].sum())
        expected_selected_positive_count = int(all_rows["positive_pair_count"].sum())

    failures: List[str] = []
    warnings: List[str] = []
    if selected_positive_total != selected_primary_positive_pair_count:
        failures.append("Selected-donor positive total differs between aggregations")
    if main_positive_total != main_primary_positive_pair_count:
        failures.append("Representative-chain positive total differs between aggregations")
    if main_primary_positive_pair_count != 173732:
        failures.append(
            "Final schema-v8 representative-chain primary positive count is not 173732"
        )
    if selected_primary_positive_pair_count != 169740:
        failures.append(
            "Final schema-v8 selected-donor primary positive count is not 169740"
        )
    if sum(row["selected_donor_positive_pair_count"] for row in donor_class_rows) != selected_primary_positive_pair_count:
        failures.append("Donor-class selected positive counts do not reconcile")
    if sum(row["representative_chain_contact_positive_pair_count"] for row in donor_class_rows) != main_primary_positive_pair_count:
        failures.append("Donor-class main-contact counts do not reconcile")
    legacy_excluded_eligible_total = sum(selected_legacy_excluded_eligible.values())
    legacy_excluded_selected_positive_total = sum(
        selected_legacy_excluded_positive.values()
    )
    legacy_excluded_main_positive_total = sum(main_legacy_excluded_positive.values())
    if expected_selected_donor_count is not None and (
        selected_primary_eligible_donor_count + legacy_excluded_eligible_total
        != expected_selected_donor_count
    ):
        failures.append(
            "Chemically corrected eligible donor total plus audited legacy "
            "exclusions does not reproduce element_funnel_counts.csv"
        )
    if expected_selected_positive_count is not None and (
        selected_primary_positive_pair_count
        + legacy_excluded_selected_positive_total
        != expected_selected_positive_count
    ):
        failures.append(
            "Chemically corrected positive total plus audited legacy exclusions "
            "does not reproduce element_funnel_counts.csv"
        )
    missing_selected_positive_ids = selected_positive_donor_ids - selected_positive_ids_found
    missing_main_positive_ids = main_positive_donor_ids - main_positive_ids_found
    if missing_selected_positive_ids:
        failures.append(
            f"{len(missing_selected_positive_ids)} selected positive donor IDs were absent "
            "from donor_site_background"
        )
    if missing_main_positive_ids:
        failures.append(
            f"{len(missing_main_positive_ids)} main-scope positive donor IDs were absent "
            "from donor_site_background"
        )
    if backbone_background_by_residue["PRO"]["eligible_site_count"] != 0:
        failures.append("PRO was unexpectedly assigned an internal Backbone N-H donor")
    if duplicate_positive_rows:
        warnings.append(
            f"{duplicate_positive_rows} conformer-level positive rows were collapsed by "
            "spatial_pair_id"
        )
    if legacy_excluded_eligible_total or legacy_excluded_selected_positive_total:
        warnings.append(
            "Earlier element tables included nonstandard residues assigned to a "
            "standard donor class and/or internal Pro N classified as Backbone N-H; "
            "the residue/donor tables apply the stricter chemically correct scope"
        )

    write_csv(out / "residue_contribution.csv", residue_rows)
    write_csv(out / "residue_atom_propensity.csv", atom_rows)
    write_csv(out / "donor_class_propensity.csv", donor_class_rows)
    write_csv(out / "donor_class_geometry.csv", geometry_rows)
    write_csv(out / "backbone_nh_by_residue.csv", backbone_rows)

    analysis_metadata = {
        "created_utc": datetime.now(timezone.utc).isoformat(),
        "script": Path(__file__).name,
        "background_root": str(root),
        "background_schema_version": background_metadata.get("output_schema_version"),
        "analysis_units": {
            "residue": "residue_position_id",
            "donor_site": "donor_site_id",
            "positive_pair": "spatial_pair_id",
        },
        "bootstrap_replicates": args.bootstrap,
        "bootstrap_seed": args.seed,
        "bootstrap_independent_unit": "PDB structure",
        "primary_donor_scope": (
            "standard-amino-acid neutral donor classes; Thiol S-H restricted to "
            "putative_free_thiol; charged side-chain N-H, N-terminal N-H and "
            "Other or non-standard excluded"
        ),
        "rate_scope": (
            "donor on a PISCES-selected coordinate chain; acceptor on any chain"
        ),
        "representative_chain_contact_scope": (
            "either donor or acceptor on a PISCES-selected coordinate chain"
        ),
        "microheterogeneity": (
            "raw, primary-position and residue-variant-weighted estimands are "
            "reported separately"
        ),
        "geometry_scope": (
            "descriptive distributions of one representative row per unique "
            "positive spatial_pair_id; no pair-level independence is assumed"
        ),
        "hydrogen_bond_boundary": (
            "backbone_nh_by_residue does not test conventional hydrogen-bond "
            "competition or strength"
        ),
        "legacy_element_scope_reconciliation": (
            "Earlier element tables did not require a standard residue name and "
            "did not exclude internal Pro N from Backbone N-H. These rows are "
            "audited in qc_report.json and excluded here."
        ),
    }
    (out / "analysis_metadata.json").write_text(
        json.dumps(analysis_metadata, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )

    qc_report = {
        "status": "fail" if failures else "pass",
        "background_root": str(root),
        "output_directory": str(out),
        "structures_in_spatial_dataset": len(spatial_files),
        "structures_in_bootstrap_universe": len(pdb_ids),
        "bootstrap_replicates": args.bootstrap,
        "selected_primary_eligible_donor_site_count": selected_primary_eligible_donor_count,
        "selected_primary_positive_pair_count": selected_primary_positive_pair_count,
        "representative_chain_primary_positive_pair_count": main_primary_positive_pair_count,
        "selected_positive_donor_site_count": len(selected_positive_donor_ids),
        "representative_chain_positive_donor_site_count": len(main_positive_donor_ids),
        "duplicate_positive_conformer_rows_collapsed": duplicate_positive_rows,
        "duplicate_donor_conformer_rows_collapsed": duplicate_donor_conformer_rows,
        "expected_selected_eligible_donor_site_count_from_element_table": expected_selected_donor_count,
        "expected_selected_positive_pair_count_from_element_table": expected_selected_positive_count,
        "legacy_scope_excluded_eligible_donor_site_count": legacy_excluded_eligible_total,
        "legacy_scope_excluded_selected_positive_pair_count": legacy_excluded_selected_positive_total,
        "legacy_scope_excluded_representative_chain_positive_pair_count": legacy_excluded_main_positive_total,
        "legacy_scope_selected_eligible_exclusions_by_reason_residue_class_element": dict(
            sorted(selected_legacy_excluded_eligible.items())
        ),
        "legacy_scope_selected_positive_exclusions_by_reason_residue_class_element": dict(
            sorted(selected_legacy_excluded_positive.items())
        ),
        "legacy_scope_representative_chain_positive_exclusions_by_reason_residue_class_element": dict(
            sorted(main_legacy_excluded_positive.items())
        ),
        "missing_selected_positive_donor_ids": len(missing_selected_positive_ids),
        "missing_representative_chain_positive_donor_ids": len(missing_main_positive_ids),
        "failures": failures,
        "warnings": warnings,
        "table_rows": {
            "residue_contribution": len(residue_rows),
            "residue_atom_propensity": len(atom_rows),
            "donor_class_propensity": len(donor_class_rows),
            "donor_class_geometry": len(geometry_rows),
            "backbone_nh_by_residue": len(backbone_rows),
        },
    }
    (out / "qc_report.json").write_text(
        json.dumps(qc_report, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )

    print(json.dumps(qc_report, indent=2, sort_keys=True))
    print(f"Output: {out}")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
